// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi key-value db
example


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 0.1.0

    Consumes:
    - application/octet-stream

    Produces:
    - application/octet-stream

swagger:meta
*/
package restapi
