// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

var (
	// SwaggerJSON embedded version of the swagger document used at generation time
	SwaggerJSON json.RawMessage
	// FlatSwaggerJSON embedded flattened version of the swagger document used at generation time
	FlatSwaggerJSON json.RawMessage
)

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/octet-stream"
  ],
  "produces": [
    "application/octet-stream"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "example",
    "title": "key-value db",
    "version": "0.1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/values/{key}": {
      "get": {
        "summary": "Read from DB",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Value by key",
            "schema": {
              "$ref": "#/definitions/Value"
            }
          },
          "404": {
            "description": "Key not found"
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      },
      "post": {
        "summary": "Write to DB",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          },
          {
            "name": "value",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Value"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "definitions": {
    "Value": {
      "type": "string",
      "format": "binary"
    }
  }
}`))
	FlatSwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/octet-stream"
  ],
  "produces": [
    "application/octet-stream"
  ],
  "schemes": [
    "http"
  ],
  "swagger": "2.0",
  "info": {
    "description": "example",
    "title": "key-value db",
    "version": "0.1.0"
  },
  "basePath": "/v1",
  "paths": {
    "/values/{key}": {
      "get": {
        "summary": "Read from DB",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "Value by key",
            "schema": {
              "$ref": "#/definitions/Value"
            }
          },
          "404": {
            "description": "Key not found"
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      },
      "post": {
        "summary": "Write to DB",
        "parameters": [
          {
            "type": "string",
            "name": "key",
            "in": "path",
            "required": true
          },
          {
            "name": "value",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Value"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK"
          },
          "default": {
            "description": "Unexpected error"
          }
        }
      }
    }
  },
  "definitions": {
    "Value": {
      "type": "string",
      "format": "binary"
    }
  }
}`))
}
