swagger: "2.0"
info:
  title: key-value db
  description: example
  version: 0.1.0

basePath: /v1

schemes:
- http

consumes:
  - application/octet-stream

produces:
  - application/octet-stream


definitions:

  Value:
    type: string
    format: binary


paths:

  /values/{key}:

    get:
      summary: Read from DB
      parameters:
        - name: key
          in: path
          type: string
          required: true
      responses:
        '200':
          description: Value by key
          schema:
            $ref: "#/definitions/Value"
        '404':
          description: Key not found
        default:
          description: Unexpected error

    post:
      summary: Write to DB
      parameters:
        - name: key
          in: path
          type: string
          required: true
        - name: value
          in: body
          schema:
            $ref: "#/definitions/Value"
          required: true
      responses:
        '200':
          description: OK
        default:
          description: Unexpected error


