// Code generated by go-swagger; DO NOT EDIT.

package models

import "io"

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// Value value
// swagger:model Value
type Value io.ReadCloser
